-- Referencia para MySQL. db.php crea estas tablas automáticamente; solo úsalo si prefieres crearlas a mano.
CREATE TABLE IF NOT EXISTS mazos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  es_default TINYINT NOT NULL DEFAULT 0,
  creado DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS cartas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  mazo_id INT NOT NULL,
  numero INT NOT NULL,
  nombre VARCHAR(80) NOT NULL,
  imagen VARCHAR(255) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS partidas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  codigo VARCHAR(6) NOT NULL UNIQUE,
  mazo_id INT NOT NULL,
  estado VARCHAR(12) NOT NULL DEFAULT 'lobby',
  orden_cartas TEXT NULL,
  indice_actual INT NOT NULL DEFAULT -1,
  auto TINYINT NOT NULL DEFAULT 0,
  intervalo_seg INT NOT NULL DEFAULT 6,
  ganador_id INT NULL,
  creada DATETIME DEFAULT CURRENT_TIMESTAMP,
  actualizada DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS jugadores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  partida_id INT NOT NULL,
  nombre VARCHAR(30) NOT NULL,
  token VARCHAR(40) NOT NULL UNIQUE,
  tablero TEXT NOT NULL,
  creado DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS marcas (
  jugador_id INT NOT NULL,
  carta_id INT NOT NULL,
  marcada_en DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (jugador_id, carta_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS gritos (
  id INT AUTO_INCREMENT PRIMARY KEY,
  partida_id INT NOT NULL,
  jugador_id INT NOT NULL,
  valido TINYINT NOT NULL,
  atendido TINYINT NOT NULL DEFAULT 0,
  hora DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
